apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: keycloak
  labels:
    service: keycloak
    layer: security
spec:
  tls:
    - hosts:
      - dwaauth.mctplatform.click
      secretName: dwaauth-mctplatform-secret
  rules:
    - host: dwaauth.mctplatform.click
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
